[prune]
  non-go = true
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"  

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.5.0"

[[override]]
  name = "gopkg.in/src-d/go-billy.v4"
  version = "4.2.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "go.etcd.io/bbolt"
  version = "v1.3.1-etcd.8"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.26"

[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"
