[prune]
  non-go = true
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"  

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.4.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.10"

[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[[override]]
  name = "github.com/docker/libnetwork"
  revision = "19279f0492417475b6bfbd0aa529f73e8f178fb5"
